---
- name: Validate Network State
  hosts: "{{ target_hosts }}"
  connection: httpapi
  gather_facts: false

  tasks:
    - name: Import Global Vars
      ansible.builtin.include_vars: "{{ item }}"
      with_items:
        - "../global_vars/global_dc_vars.yml"
        
    - name: validate states on EOS devices
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state
      vars:
        use_anta: true
        save_catalog: true
